#! aplikasi data siswa sederhana menggunakan linked list python
 
import os 
import sys 
 
class Mahasiswa: 
        nim=""
        nama="" 
pilih = 0 
dataSiswa = [] 
 
 def menu():
    os.system('clear')
    print("Menu Aplikasi Data LinkedList python") 
    print("-----------------------------------------") 
    print("1. Input Data Siswa") 
    print("2. Tampilkan Data Siswa") 
    print("3. Update Data Siswa") 
    print("4. Hapus Data Siswa") 
    print("5. Author") 
    print("6. Keluar Aplikasi") 
    pilih = int(input("Masukkan pilihan anda : ")) 
    if pilih == 1: 
        pilih1() 
        menu() 
         
    elif pilih == 2: 
        pilih1() 
        input("Kembali Ke Menu Utama") 
        menu()    

elif pilih == 3: 
        index_update=-1 
        tampil() 
        id_edit = int(input("Input Nim Yang Akan Di Update ")) 
        for a in range (0, len(dataSiswa)): 
            if id_edit == dataSiswa[a].nim: 
                index_update = a  
                break 
        if(index_update > -1): 
            print("INPUT DATA SISWA YANG DI UPDATE ") 
            siswa = Mahasiswa() 
            siswa.nim = (int(input("msukkan nim : "))) 
            siswa.nama = (input("masukkan nama siswa : ")) 
            dataSiswa[index_update] = siswa 
            print("Berhasil Update Data Siswa") 
        else : print("Nim Tidak Ditemukan") 
        input("Kembali Ke Menu Utama") 
        menu()  
    elif pilih == 4 :
        os.system('clear');
        index_delete=-1
        tampil()
        id_hapus = int(input("Input Nim yang di hapus : "))
        for a in range(0, len(dataSiswa)):
            if id_hapus == dataSiswa[a].nim:
                        index_update = a
                        break
        if(index_delete > -1):
            del dataSiswa[index_delete]
            print("Data Telah Di Hapus")
        else : print ("Data Telah Di Hapus")
        input("Kembali ke Menu Utama")
        menu()
    elif pilih == 5 : 
        Author() 
        input("\n\n Kembali Ke Menu Utama")
        menu()
    elif pilih == 6 :
        sys.exit()

def Author():    
    os.system('clear');
    print("Nirwana Syahputri")
    print("Azmi Sakinah")
    print("Putri Ramadhani")


def tampil(): 
    os.system('clear'); 
    print("DATA MAHASISWA") 
    for Data in dataSiswa: 
        print("Nim : "+str(Data.nim)) 
        print("Nama : "+ Data.nama) 
        print("----------------------------") 
         
def pilih1(): 
    ulang = 'Y' 
    while ulang in("y", "Y"): 
        os.system('clear'); 
        siswaBaru = Mahasiswa() 
        print("Input Data Mahasiswa ") 
        siswaBaru.nim = (int(input("Masukkan Nim : "))) 
        siswaBaru.nama = (inpucxt("Masukkan Nama Siswa : ")) 
        dataSiswa.append(siswaBaru) 
        ulang = input ("Apakah Anda Ingin Mengulang (Y/T)? ") 
 
menu()
